name: showdown
description: "An app for keeping track of points when refereeing a showdown game."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0-180.3.beta <4.0.0"

dependencies:
  backstreets_widgets: ^0.16.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  form_builder_validators: ^11.0.0
  json_annotation: ^4.9.0
  recase: ^4.1.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  uuid: ^4.4.2
  wakelock_plus: ^1.1.6

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.2

flutter:
  uses-material-design: true
